#!/usr/bin/env bash
# Loops from 1 to 10
# Displays "bad luck" for the 4th iteration
# Displays "good luck" for the 8th iteration
# Displays "Best School" for all other iterations

limit=0

while [ $limit -lt 10 ]
do
  if [ $limit -eq 3 ]
  then
    echo "bad luck"
  elif [ $limit -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( limit++ ))
done
