#!/usr/bin/env bash
# Displays numbers from 1 to 20
# Displays "bad luck from China" for the 4th iteration
# Displays  "bad luck from Japan" for the 9th iteration
# Displays  "bad luck from Italy" for the 17th loop iteration

limit=1

while [ $limit -le 20 ]
do
  echo "$limit"
  case $limit in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( limit++ ))
done
