#!/usr/bin/env bash
# Server 411997-web-01 login commands

# Setting up the SSH agent
eval $("ssh-agent")

# Path to identityFile
ssh-add ~/.ssh/school

# Username and IP Address 
ssh ubuntu@52.91.135.216
