#!/usr/bin/env bash
# Run Nginx as Nginx

# set a user in the config
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 by 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# grant owner read and write permissions
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx so kill the process if it is running
pkill apache2
# start the nginx service with the new nginx user
sudo -u nginx service nginx start
